---
# tasks file for ansible-role-ubuntu-setup

# Additional PPA keys.
- name: Add keys for non-stock repositories.
  apt_key:
    keyserver: "{{ item.keyserver }}"
    id: "{{ item.fingerprint }}"
  with_items: "{{ ppas }}"
  tags:
    - packages
    - ppas

# Additional repositories.
- name: Add non-stock repositories.
  apt_repository:
    repo: "{{ item.source }}"
    state: present
  with_items: "{{ ppas }}"
  tags:
    - packages
    - ppas

# Various packages.
- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 86400
  tags:
    - packages

- name: Install packages.
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ apt_packages }}"
  tags:
    - packages

# Individual packages (i.e. with no ppa).
- name: Install non-ppa deb packages.
  apt:
    deb: "{{ item }}"
  with_items: "{{ no_ppa_packages }}"


# Remove packages that should not be present.
- name: Uninstall packages.
  apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ apt_removals }}"

# More complex things.
#
# @todo: set up Dropbox daemon install.

# Install vagrant plugins.
# @todo: check for vagrant existence first.
- name: Install vagrant plugins.
  shell: "vagrant plugin install {{ item }}"
  with_items:
    - "vagrant-hostsupdater"
    - "vagrant-vbguest"
  become: "ctorgalson"

# System-level configuration.

- name: Make sure synapse is called with `Exec=synapse --display:=0`.
  lineinfile:
    dest: "/usr/share/applications/synapse.desktop"
    regexp: "^Exec=synapse"
    line: "Exec=synapse --display:=0"
  when: "'synapse' in apt_packages"
  become: True

- name: Makes sure expected directories, links and (empty) files are present.
  file:
    src: "{{ item.src | default('') }}"
    dest: "{{ item.dest }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner | default(default_user) }}"
    group: "{{ item.group | default(default_group) }}"
  with_items: "{{ default_files }}"
  tags:
    - setup

- name: Set gtk theme.
  command: "gsettings set org.gnome.desktop.interface gtk-theme {{ gtk_theme }}"
  become: "ctorgalson"
  tags:
    - theme

- name: Set gtk icon theme.
  command: "gsettings set org.gnome.desktop.interface icon-theme {{ icon_theme }}"
  become: "ctorgalson"
  tags:
    - theme

- name: Set window theme.
  command: "gsettings set org.gnome.desktop.wm.preferences theme {{ theme }}"
  become: "ctorgalson"
  tags:
    - theme
